document.write('<style>');
document.write('.nav_button {');
document.write('    height: 30px;');
document.write('    width: 100px;');
document.write('    border: 2px;');
document.write('    margin-right: 2px;');
document.write('    margin-bottom: 5px;');
document.write('    color : white;');
document.write('    background-color: lightseagreen;');
document.write('');
document.write('    font-size: 20px;');
document.write('    font-family: \'Gill Sans\', \'Gill Sans MT\', Calibri, \'Trebuchet MS\', sans-serif;');
document.write('}');
document.write('');
document.write('.nav_button:hover {');
document.write('    background-color: rgb(19, 105, 100);');
document.write('}');
document.write('</style>');
document.write('<button class="nav_button" onclick="window.location.href=\'../homepage/homepage.html\'">Home</button>');
document.write('<button class="nav_button" onclick="window.location.href=\'../clicker/cheapclicker.html\'">Clicker</button>');
document.write('<button class="nav_button" onclick="window.location.href=\'../cringe/cringepage.html\'">Cringe</button>');
document.write('<button class="nav_button" onclick="window.location.href=\'../pong/pong.html\'">Pong</button>');
document.write('<button class="nav_button" onclick="window.location.href=\'../serversim/server.html\'">ServerSim</button>');
